# $ docker-compose up
version: "3"
services:
  msa-apigateway:
    image: extact-io/msa-apigateway:latest
    container_name: "msa-apigateway"
    ports:
      - "7001:7001"
    environment:
      - JWT_FILTER=true # JWT Auth and RBAC
      - ENV_RMS_SERVICE_URL_ITEM=http://msa-service-item:7002
      - ENV_RMS_SERVICE_URL_RESERVATION=http://msa-service-reservation:7003
      - ENV_RMS_SERVICE_URL_USER=http://msa-service-user:7004
      - TRACING_ENABLED=true  # for Helidon config
      - TRACING_HOST=jeager   # for Helidon config
  msa-service-item:
    image: extact-io/msa-service-item:latest
    container_name: "msa-service-item"
    environment:
      - TRACING_ENABLED=true
      - TRACING_HOST=jeager
  msa-service-reservation:
    image: extact-io/msa-service-reservation:latest
    container_name: "msa-service-reservation"
    environment:
      - ENV_RMS_SERVICE_URL_ITEM=http://msa-service-item:7002
      - ENV_RMS_SERVICE_URL_USER=http://msa-service-user:7004
      - TRACING_ENABLED=true
      - TRACING_HOST=jeager
  msa-service-user:
    image: extact-io/msa-service-user:latest
    container_name: "msa-service-user"
    environment:
      - TRACING_ENABLED=true
      - TRACING_HOST=jeager
  jeager:
    image: jaegertracing/all-in-one:1.39
    ports:
      - "6831:6831/udp" # accept jaeger.thrift over compact thrift protocol
      - "5778:5778"     # serve configs
      - "16686:16686"   # serve frontend
      - "14250:14250"   # accept model.proto
      - "14268:14268"   # accept jaeger.thrift directly from clients
      - "9411:9411"     # Zipkin compatible endpoint (optional)
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
