# $ docker-compose up
version: "3"
services:
  msa-apigateway:
    image: extactmame/msa-apigateway:latest
    container_name: "msa-apigateway"
    ports:
      - "80:7001"
      - "443:7011"
    environment:
      - ENV_RMS_SERVICE_URL_ITEM=http://msa-service-item:7002
      - ENV_RMS_SERVICE_URL_RESERVATION=http://msa-service-reservation:7003
      - ENV_RMS_SERVICE_URL_USER=http://msa-service-user:7004
      - ENV_RMS_SEC_TLS_PASSPHRASE=mamezou  # override with environment variables for secret
      - ENV_RMS_SEC_JWT_FILTER=true         # JWT Auth and RBAC
      - ENV_RMS_SEC_JWT_SECRETKEY=/resources/secrets/jwt.key
      - ENV_RMS_SEC_JWT_PUBLICKEY=/resources/secrets/jwt.pub.key
      - ENV_RMS_SEC_TLS_FILE=/resources/app_extact_io.p12
      - TRACING_ENABLED=true
      - TRACING_HOST=jeager
    volumes:
      - /etc/letsencrypt/live/app.extact.io/app_extact_io.p12:/resources/app_extact_io.p12
  msa-service-item:
    image: extactmame/msa-service-item:latest
    container_name: "msa-service-item"
    environment:
      - ENV_RMS_H2_USER=sa    # override with environment variables for secret
      - ENV_RMS_H2_PASSWORD=  # override with environment variables for secret
      - ENV_RMS_H2_SCRIPT=classpath:init-rms-demo.ddl
      - TRACING_ENABLED=true
      - TRACING_HOST=jeager
  msa-service-reservation:
    image: extactmame/msa-service-reservation:latest
    container_name: "msa-service-reservation"
    environment:
      - ENV_RMS_SERVICE_URL_ITEM=http://msa-service-item:7002
      - ENV_RMS_SERVICE_URL_USER=http://msa-service-user:7004
      - ENV_RMS_H2_USER=sa    # override with environment variables for secret
      - ENV_RMS_H2_PASSWORD=  # override with environment variables for secret
      - ENV_RMS_H2_SCRIPT=classpath:init-rms-demo.ddl
      - TRACING_ENABLED=true
      - TRACING_HOST=jeager
  msa-service-user:
    image: extactmame/msa-service-user:latest
    container_name: "msa-service-user"
    environment:
      - ENV_RMS_H2_USER=sa    # override with environment variables for secret
      - ENV_RMS_H2_PASSWORD=  # override with environment variables for secret
      - ENV_RMS_H2_SCRIPT=classpath:init-rms-demo.ddl
      - TRACING_ENABLED=true
      - TRACING_HOST=jeager
  jeager:
    image: jaegertracing/all-in-one:1.39
    ports:
      - "6831:6831/udp" # accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # accept jaeger.thrift over binary thrift protocol
      - "5778:5778"     # serve configs
      - "16686:16686"   # serve frontend
      - "14250:14250"   # accept model.proto
      - "14268:14268"   # accept jaeger.thrift directly from clients
      - "14269:14269"   #
      - "9411:9411"     # Zipkin compatible endpoint (optional)
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
