version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/apps/msa-apigateway/deployment
permissions:
  - object: /usr/local/apps/msa-apigateway/deployment/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  ApplicationStart:
    - location: scripts/docker_run.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/docker_stop.sh
      timeout: 300
      runas: root
