version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/apps/msa-apigateway/deployment
hooks:
  ApplicationStart:
    - location: scripts/docker_run.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/docker_stop.sh
      timeout: 300
      runas: root
