# Workflow - build, publish jar and image to GitHub Packages for this repository(msa-rms-apigateway)
name: deploy-workflow

on:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: extact-io/msa-rms-parent/.github/workflows/deploy-job.yml@main
    with:
      repo: ${{ github.repository }}
      with_image: true
      deploy_type: ec2
      aws_appname: msa-apigateway
    secrets: inherit
