# Workflow - build, publish jar and image to GitHub Packages for this repository(msa-rms-apigateway)
name: deploy-workflow

on:
  workflow_dispatch:
    inputs:
      skip-test:
        description: skip step?
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      skip-test:
        required: true
        type: boolean

jobs:
  call-build:
    uses: extact-io/msa-rms-parent/.github/workflows/build-to-repo-job.yml@main
    with:
      repo: ${{ github.repository }}
      aws-appname: msa-apigateway
      skip-test: ${{ inputs.skip-test }}
      with-image: true
    secrets: inherit
  call-deploy:
    uses: extact-io/msa-rms-parent/.github/workflows/deploy-to-ec2-job.yml@main
    with:
      repo: ${{ github.repository }}
      aws-appname: msa-apigateway
    secrets: inherit
